#!/usr/bin/bash

build=""
if [ -f /usr/bin/ninja ]; then
    build="-G Ninja"
fi

options="-DKokkos_ENABLE_OPENMP=ON"
export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

if [[ $1 == "--cuda" ]]; then
    options="-DKokkos_ENABLE_CUDA=ON"
fi

if [[ $1 == "--hip" ]]; then
    options="-DKokkos_ENABLE_HIP=ON -DKokkos_ENABLE_ROCTHRUST=OFF"
    export CC=hipcc
    export CXX=hipcc
    export hip_DIR=/opt/rocm/lib/cmake/hip/
fi

cmake -B build -DCMAKE_BUILD_TYPE=Release $options $build || exit
cmake --build build || exit
time build/src/main || exit