#!/usr/bin/bash

dir="build"

build=""
if [ -f /usr/bin/ninja ]; then
    build="-G Ninja"
fi

options="-DKokkos_ENABLE_OPENMP=ON"
export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

if [[ $1 == "--cuda" ]]; then
    options="-DKokkos_ENABLE_CUDA=ON -DKokkosKernels_ENABLE_TPL_CUBLAS=ON -DKokkosKernels_ENABLE_TPL_CUSOLVER=ON"
    dir=build-cuda
fi

if [[ $1 == "--hip" ]]; then
    options="-DKokkos_ENABLE_HIP=ON -DKokkos_ENABLE_ROCTHRUST=OFF"
    export CC=hipcc
    export CXX=hipcc
    export hip_DIR=/opt/rocm/lib/cmake/hip/
    dir=build-hip
fi

cmake -B $dir -DCMAKE_BUILD_TYPE=Release -DKokkosKernels_ENABLE_COMPONENT_LAPACK=ON $options $build || exit
cmake --build $dir || exit
time $dir/src/main || exit